[project]
name = "ips-scraper"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "pkb-pmj", email = "pkb.pmj@gmail.com"},
]
dependencies = ["beautifulsoup4>=4.13.5"]
requires-python = "==3.13.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
